channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=24.3.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.1.0
  - numpy==2.1.3
  - pandas==2.2.3
  - pydantic==2.9.2
  - ruamel-yaml==0.18.6
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - strictyaml==1.7.3
  - xgboost==2.1.2
name: mlflow-env
