name: Build and Run Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: docker build -t chatbot-app ./chatbot

    # Step 4: Run the Docker container
    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name chatbot-app chatbot-app
        sleep 10 # Wait for the container to start

    # Step 5: Test the application
    - name: Test the application
      run: |
        curl -f http://localhost:8000 || exit 1

    # Step 6: Cleanup
    - name: Stop and remove container
      if: always()
      run: |
        docker stop chatbot-app
        docker rm chatbot-app
