apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      labels:
        app: myapp-pod
      annotations:
        prometheus.io/scrape: "true"        # Enable Prometheus scraping
        prometheus.io/port: "8001"         # Metrics port
        prometheus.io/path: "/api/v1/metrics"     # Metrics path
    spec:
      containers:
      - image: kpavan2004/driver_delivery_time_pred-fastapi
        name: mycontainer
        ports:
        - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-app
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: myapp-pod
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  targetCPUUtilizationPercentage: 80
