apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: kpavan2004/mlflow_server:latest # Replace with a custom MLflow image if needed
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_BACKEND_STORE_URI
          value: sqlite:///mlflow/mlflow.db # Replace with MySQL or PostgreSQL URI for production
        - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
          value: s3://pk-capstone-bucket-01/MLflow-data/ # Replace with your artifact store path
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: AWS_DEFAULT_REGION
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow
      volumes:
      - name: mlflow-data
        emptyDir: {} # Use PersistentVolumeClaim for persistent storage in production
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer # Use LoadBalancer to expose MLflow UI externally
