# Prometheus ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 20s
    scrape_configs:
      - job_name: 'delivery_time_pred'
        metrics_path: '/api/v1/metrics'
        scheme: 'http' # For localhost it should be http
        scrape_interval: 20s # override default value
        scrape_timeout: 20s # override default value
        static_configs:
          - targets: ['192.168.1.19:8001']

---
# Prometheus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      - name: prometheus-data
        # persistentVolumeClaim:
        #   claimName: prometheus-pvc
        emptyDir: {}  # Replace with PersistentVolumeClaim for persistent storage

---
# Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    # nodePort: 30002    # Node Port/Host Port
  type: LoadBalancer
