apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-demand-st-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-demand-st-app
  template:
    metadata:
      labels:
        app: delivery-demand-st-app
    spec:
      containers:
      - name: stapp-delivery-demand
        image: kpavan2004/delivery_demand_st_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8503
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-demand-st-app
spec:
  type: LoadBalancer
  selector:
    app: delivery-demand-st-app
  ports:
  - port: 8503
    targetPort: 8503