name: Build and Run Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  docker-build-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up QEMU (for cross-platform builds)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    # Step 3: Set up Docker Buildx
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./ui_app/chatbot  # Set the correct path to the Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: mahan0227/foodpredicto:latest
