name: CI CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  train:
    env:
      RE_TRAIN: Yes      # Re-train 'Yes' / 'No'?
    needs: mlflow
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'	
    - name: Install mlflow Dependencies
      run: |
        pip install mlflow
    - name: Start MLflow Server
      run: |
        nohup mlflow ui --host 0.0.0.0 --port 5000 &
    - name: Install app dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train and save pipeline
      run: python delivery_time_model/train_pipeline.py
    - uses: actions/upload-artifact@v3
      with:
        name: my-trained-pipeline
        path: delivery_time_model/trained_models

  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v3
      with:
        name: my-trained-pipeline
        path: delivery_time_model/trained_models
    - name: Install dependencies
      run: pip install -r requirements/test_requirements.txt
    - name: Test with pytest
      run: pytest

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v3
      with:
        name: my-trained-pipeline
        path: delivery_time_model/trained_models
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v3
      with:
        name: my-build-package
        path: dist/*.whl

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: my-build-package
        path: delivery_time_model_api

    - name: Login to Docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker build . -f Dockerfile -t $DOCKER_USER/driver_delivery_time_pred-fastapi:latest

    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker push $DOCKER_USER/driver_delivery_time_pred-fastapi

    - name: Logout to Docker hub
      run: docker logout

  deploy:
    needs: [train, test, build, push-image]
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/driver_delivery_time_pred-fastapi
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f app_container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d -p 8001:8001 --name app_cont $DOCKER_USER/driver_delivery_time_pred-fastapi
  mlflow:
    runs-on: ubuntu-latest
    steps:
      - name: Install mlfow dependencies
        run: pip install mlflow
      - name: Run the mlfow ui
        run: mlflow ui --host 0.0.0.0 --port 5000
