name: Concurrency Test Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:
  repository_dispatch:
    types:
      - grafana_trigger
  schedule:
    - cron: "0 0 1 * *"  # Runs on the 1st day of every month at midnight UTC
jobs:
  pre-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Running Workflows
        id: check
        run: |
          runs=$(gh run list --workflow "${{ github.workflow }}" --branch "${{ github.ref_name }}" --json status --jq '.[] | select(.status=="in_progress")')
          if [ -n "$runs" ]; then
            echo "A workflow is already running. Exiting..."
            exit 1
          fi
      - name: Proceed with Workflow
        run: echo "No running workflows. Proceeding..."
        
  test-concurrency:
    runs-on: ubuntu-latest

    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    #   cancel-in-progress: false  # Cancel previous runs in the same group

    steps:
      - name: Start Workflow
        run: echo "Starting concurrency test workflow..."

      - name: Simulate Long-Running Job
        run: |
          echo "Sleeping for 120 seconds..."
          sleep 120

      - name: Complete Workflow
        run: echo "Workflow completed!"
