name: Deploy to EKS

on:
  push:
    branches:
      - master  # Deploy when code is pushed to the main branch

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set aws_default_region $AWS_DEFAULT_REGION

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name myCluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f myapp-deployment.yaml

    - name: Verify Deployment
      run: |
        kubectl get all
