name: Grafana Triggered Testing
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - grafana_trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        run: echo "Pipeline triggered by Grafana"
