name: Grafana Trigger Testing
on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
    types:
      - grafana_trigger
  schedule:
    - cron: "0 0 1 * *"  # Runs on the 1st day of every month at midnight UTC
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        run: echo "Pipeline triggered by Grafana"
