name: Prom Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    # needs: [train, test, build, push-image]
    runs-on: ec2
    steps:
      - uses: actions/checkout@v3
      - name: Checkout code
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Delete Old Docker Container
        run: sudo docker rm -f prom_cont || true
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          DATA_VERSION: ${{ secrets.DATA_VERSION }}
        run: sudo docker run -it -d -p 9090:9090 --name=prom_cont -e DOCKER_USER=$DOCKER_USER -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION -e GH_USERNAME=$GH_USERNAME -e GH_ACCESS_TOKEN=$GH_ACCESS_TOKEN -e DATA_VERSION=$DATA_VERSION -v "./workspaces/driver_demand_prediction_capstone/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml" prom/prometheus
